#!/usr/bin/python3

from picamera import PiCamera
import time

def main():
	camera = PiCamera()
	camera.start_preview(fullscreen = False, window = (100, 20, 640, 480))
	time.sleep(5)
	camera.stop_preview()

if __name__ == "__main__":
	main()
